### ISSUE TITLE
大佬 刷到一定播放量之后就不能再刷，有解决办法了吗？

### ISSUE THREAD

**Issue by tiandao716** [zhizhuodemao/bilibili_spider#1]
我刚刷了一百多播放量就刷不动了，换IP也不行。
然后我去买了几百播放量，发现他们那机刷却还是可以继续刷，就是速度慢

**Comment by zhizhuodemao** [comment]
你把app接口逆向了,流程差不多的，还能继续刷几千

**Comment by zhizhuodemao** [comment]
> 我刚刷了一百多播放量就刷不动了，换IP也不行。 然后我去买了几百播放量，发现他们那机刷却还是可以继续刷，就是速度慢

你把app接口逆向了，还能继续刷

**Comment by zhizhuodemao** [comment]
> 我刚刷了一百多播放量就刷不动了，换IP也不行。 然后我去买了几百播放量，发现他们那机刷却还是可以继续刷，就是速度慢

一共能刷个几千播放量，bilibili有风控的

**Comment by zhizhuodemao** [comment]
github回复了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月9日(周二) 上午10:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhizhuodemao/bilibili_spider] 大佬 刷到一定播放量之后就不能再刷，有解决办法了吗？ (Issue #1)




 
我刚刷了一百多播放量就刷不动了，换IP也不行。
 然后我去买了几百播放量，发现他们那机刷却还是可以继续刷，就是速度慢

**Comment by tiandao716** [comment]
刷不了几千播放量。昨晚我IP换了几百个 就刷了一百个左右就不在新增播放量了。怪不得那些平台还可以刷，原来是逆向了才能继续刷的

**Comment by tiandao716** [comment]
> 刷不了几千播放量。昨晚我IP换了几百个 就刷了一百个左右就不在新增播放量了。怪不得那些平台还可以刷，原来是逆向了才能继续刷的

**Comment by tiandao716** [comment]
嗯嗯 非常感谢大佬的帮助，你的专业解答让我茅塞顿开 我今晚试试

**Comment by zaq1019407290** [comment]
可以用嘛？可以提供下嘛
